### ISSUE TITLE
Error while running make cf command.

### ISSUE THREAD

**Issue by rohitsakala** [cloudfoundry/grootfs#13]
Hi,

I am facing the following error while running ```make cf``` command on SLES12 os with s390x architecture.

```compilation-grootfs > store/filesystems/filesystems.go:30:17: invalid operation: statfs.Type != fsType (mismatched types uint32 and int64)
compilation-grootfs > make: *** [Makefile:8: all] Error 2```

**Comment by julz** [comment]
Hi @rohitsakala - it sounds like you're trying to port Cloud Foundry to work on the s390 (since afaik this is not something the open source Cloud Foundry supports right now). This is very cool, but unfortunately I'm afraid our team is likely to be of limited assistance here: we just don't have the skill or knowledge to support this. If you have more specific questions or problems we'd be happy to try to answer them (and feel free to join #garden in slack.cloudfoundry.org), but I don't think we can really help - in the open source team - with such a high level question, given s390 is not a supported platform.

**Comment by rohitsakala** [comment]
Hi @julz 

Thank you for the answer and your intention is correct.
Sorry, I didn't paste the full error. Now I have edited the issue. Let me know if that is something solvable.
